// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.14.0
// source: keywordEnc.proto

package keywordEnc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// KeywordEncServerClient is the client API for KeywordEncServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeywordEncServerClient interface {
	KeywordEnc(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type keywordEncServerClient struct {
	cc grpc.ClientConnInterface
}

func NewKeywordEncServerClient(cc grpc.ClientConnInterface) KeywordEncServerClient {
	return &keywordEncServerClient{cc}
}

func (c *keywordEncServerClient) KeywordEnc(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/keywordEnc.keywordEncServer/KeywordEnc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeywordEncServerServer is the server API for KeywordEncServer service.
// All implementations must embed UnimplementedKeywordEncServerServer
// for forward compatibility
type KeywordEncServerServer interface {
	KeywordEnc(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedKeywordEncServerServer()
}

// UnimplementedKeywordEncServerServer must be embedded to have forward compatible implementations.
type UnimplementedKeywordEncServerServer struct {
}

func (UnimplementedKeywordEncServerServer) KeywordEnc(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeywordEnc not implemented")
}
func (UnimplementedKeywordEncServerServer) mustEmbedUnimplementedKeywordEncServerServer() {}

// UnsafeKeywordEncServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeywordEncServerServer will
// result in compilation errors.
type UnsafeKeywordEncServerServer interface {
	mustEmbedUnimplementedKeywordEncServerServer()
}

func RegisterKeywordEncServerServer(s grpc.ServiceRegistrar, srv KeywordEncServerServer) {
	s.RegisterService(&KeywordEncServer_ServiceDesc, srv)
}

func _KeywordEncServer_KeywordEnc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeywordEncServerServer).KeywordEnc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keywordEnc.keywordEncServer/KeywordEnc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeywordEncServerServer).KeywordEnc(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// KeywordEncServer_ServiceDesc is the grpc.ServiceDesc for KeywordEncServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeywordEncServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "keywordEnc.keywordEncServer",
	HandlerType: (*KeywordEncServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "KeywordEnc",
			Handler:    _KeywordEncServer_KeywordEnc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "keywordEnc.proto",
}
