// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.14.0
// source: symmetricKeyEnc.proto

//option java_multiple_files = false;
//option java_package = "symmetricKeyEnc.proto";
//option java_outer_classname = "symmetricKeyEnc";

package symmetricKeyEnc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义请求参数  -对称密钥明文
type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SymmetricKey string `protobuf:"bytes,1,opt,name=symmetricKey,proto3" json:"symmetricKey,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_symmetricKeyEnc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_symmetricKeyEnc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_symmetricKeyEnc_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetSymmetricKey() string {
	if x != nil {
		return x.SymmetricKey
	}
	return ""
}

// 定义返回参数  -对称密钥密文
type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	C1 string `protobuf:"bytes,1,opt,name=C1,proto3" json:"C1,omitempty"`
	C2 string `protobuf:"bytes,2,opt,name=C2,proto3" json:"C2,omitempty"`
	C3 string `protobuf:"bytes,3,opt,name=C3,proto3" json:"C3,omitempty"`
	C4 string `protobuf:"bytes,4,opt,name=C4,proto3" json:"C4,omitempty"`
	C5 string `protobuf:"bytes,5,opt,name=C5,proto3" json:"C5,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_symmetricKeyEnc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_symmetricKeyEnc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_symmetricKeyEnc_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetC1() string {
	if x != nil {
		return x.C1
	}
	return ""
}

func (x *Response) GetC2() string {
	if x != nil {
		return x.C2
	}
	return ""
}

func (x *Response) GetC3() string {
	if x != nil {
		return x.C3
	}
	return ""
}

func (x *Response) GetC4() string {
	if x != nil {
		return x.C4
	}
	return ""
}

func (x *Response) GetC5() string {
	if x != nil {
		return x.C5
	}
	return ""
}

var File_symmetricKeyEnc_proto protoreflect.FileDescriptor

var file_symmetricKeyEnc_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x79, 0x6d, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x45, 0x6e,
	0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x73, 0x79, 0x6d, 0x6d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x4b, 0x65, 0x79, 0x45, 0x6e, 0x63, 0x22, 0x2d, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x79, 0x6d, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x79, 0x6d, 0x6d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x22, 0x5a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x43, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x43, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x43, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x43, 0x32, 0x12, 0x0e, 0x0a, 0x02, 0x43, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x43, 0x33, 0x12, 0x0e, 0x0a, 0x02, 0x43, 0x34, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x43, 0x34, 0x12, 0x0e, 0x0a, 0x02, 0x43, 0x35, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x43, 0x35, 0x32, 0x61, 0x0a, 0x15, 0x73, 0x79, 0x6d, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x4b, 0x65, 0x79, 0x45, 0x6e, 0x63, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x48, 0x0a, 0x0f,
	0x53, 0x79, 0x6d, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x45, 0x6e, 0x63, 0x12,
	0x18, 0x2e, 0x73, 0x79, 0x6d, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x45, 0x6e,
	0x63, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x73, 0x79, 0x6d, 0x6d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x45, 0x6e, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x2f, 0x73, 0x79, 0x6d, 0x6d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x45, 0x6e, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_symmetricKeyEnc_proto_rawDescOnce sync.Once
	file_symmetricKeyEnc_proto_rawDescData = file_symmetricKeyEnc_proto_rawDesc
)

func file_symmetricKeyEnc_proto_rawDescGZIP() []byte {
	file_symmetricKeyEnc_proto_rawDescOnce.Do(func() {
		file_symmetricKeyEnc_proto_rawDescData = protoimpl.X.CompressGZIP(file_symmetricKeyEnc_proto_rawDescData)
	})
	return file_symmetricKeyEnc_proto_rawDescData
}

var file_symmetricKeyEnc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_symmetricKeyEnc_proto_goTypes = []interface{}{
	(*Request)(nil),  // 0: symmetricKeyEnc.Request
	(*Response)(nil), // 1: symmetricKeyEnc.Response
}
var file_symmetricKeyEnc_proto_depIdxs = []int32{
	0, // 0: symmetricKeyEnc.symmetricKeyEncServer.SymmetricKeyEnc:input_type -> symmetricKeyEnc.Request
	1, // 1: symmetricKeyEnc.symmetricKeyEncServer.SymmetricKeyEnc:output_type -> symmetricKeyEnc.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_symmetricKeyEnc_proto_init() }
func file_symmetricKeyEnc_proto_init() {
	if File_symmetricKeyEnc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_symmetricKeyEnc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_symmetricKeyEnc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_symmetricKeyEnc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_symmetricKeyEnc_proto_goTypes,
		DependencyIndexes: file_symmetricKeyEnc_proto_depIdxs,
		MessageInfos:      file_symmetricKeyEnc_proto_msgTypes,
	}.Build()
	File_symmetricKeyEnc_proto = out.File
	file_symmetricKeyEnc_proto_rawDesc = nil
	file_symmetricKeyEnc_proto_goTypes = nil
	file_symmetricKeyEnc_proto_depIdxs = nil
}
