// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.14.0
// source: symmetricKeyEnc.proto

package symmetricKeyEnc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SymmetricKeyEncServerClient is the client API for SymmetricKeyEncServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SymmetricKeyEncServerClient interface {
	SymmetricKeyEnc(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type symmetricKeyEncServerClient struct {
	cc grpc.ClientConnInterface
}

func NewSymmetricKeyEncServerClient(cc grpc.ClientConnInterface) SymmetricKeyEncServerClient {
	return &symmetricKeyEncServerClient{cc}
}

func (c *symmetricKeyEncServerClient) SymmetricKeyEnc(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/symmetricKeyEnc.symmetricKeyEncServer/SymmetricKeyEnc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SymmetricKeyEncServerServer is the server API for SymmetricKeyEncServer service.
// All implementations must embed UnimplementedSymmetricKeyEncServerServer
// for forward compatibility
type SymmetricKeyEncServerServer interface {
	SymmetricKeyEnc(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedSymmetricKeyEncServerServer()
}

// UnimplementedSymmetricKeyEncServerServer must be embedded to have forward compatible implementations.
type UnimplementedSymmetricKeyEncServerServer struct {
}

func (UnimplementedSymmetricKeyEncServerServer) SymmetricKeyEnc(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SymmetricKeyEnc not implemented")
}
func (UnimplementedSymmetricKeyEncServerServer) mustEmbedUnimplementedSymmetricKeyEncServerServer() {}

// UnsafeSymmetricKeyEncServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SymmetricKeyEncServerServer will
// result in compilation errors.
type UnsafeSymmetricKeyEncServerServer interface {
	mustEmbedUnimplementedSymmetricKeyEncServerServer()
}

func RegisterSymmetricKeyEncServerServer(s grpc.ServiceRegistrar, srv SymmetricKeyEncServerServer) {
	s.RegisterService(&SymmetricKeyEncServer_ServiceDesc, srv)
}

func _SymmetricKeyEncServer_SymmetricKeyEnc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SymmetricKeyEncServerServer).SymmetricKeyEnc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/symmetricKeyEnc.symmetricKeyEncServer/SymmetricKeyEnc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SymmetricKeyEncServerServer).SymmetricKeyEnc(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// SymmetricKeyEncServer_ServiceDesc is the grpc.ServiceDesc for SymmetricKeyEncServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SymmetricKeyEncServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "symmetricKeyEnc.symmetricKeyEncServer",
	HandlerType: (*SymmetricKeyEncServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SymmetricKeyEnc",
			Handler:    _SymmetricKeyEncServer_SymmetricKeyEnc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "symmetricKeyEnc.proto",
}
